# INICIO - CORE PROPERTIES
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
user:
  timezone: ${TIMEZONE:America/Sao_Paulo}

spring:
  config:
    import: "optional:configtree:/mnt/secrets-store/"
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
    default-property-inclusion: NON_NULL
  main:
    allow-bean-definition-overriding: true
    banner-mode: CONSOLE
  banner:
    location: banner.txt
  # INICIO - WEB PROPERTIES
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
    httpclientfactories:
      apache:
        enabled: false
      ok:
        enabled: true
  # FIM - WEB PROPERTIES
# FIM - CORE PROPERTIES

# INICIO - ACTUATOR PROPERTIES
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
    exposure:
      include: health
  endpoint:
    health:
      enabled: true
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, ping
      show-details: "NEVER"
      probes:
        enabled: true
  health:
    ping:
      enabled: true
    diskspace:
      enabled: false
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    servicosDependentes:
      enabled: false
    redis:
      enabled: false
  # Rastreabilidade com Micrometer
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
# FIM - ACTUATOR PROPERTIES

messages:
  exception: 'classpath:/messages/global'

# INICIO - Configuracao level log
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    br:
      com:
        bank: ${LOG_LEVEL_BR_COM_bank:INFO}
    okhttp3: ${LOG_LEVEL_OKHTTP3:OFF}
    org:
      springframework: ${LOG_LEVEL_ORG_SPRINGFRAMEWORK:INFO}

bank:
  # Engenharia de Software DS, biblioteca de logs do bank, documentacao no confluence: https://confluence.bank.com.br:8443/pages/viewpage.action?pageId=290426770
  enge:
    # LogCloud
    logcloud:
      # Técnico
      tecnico.log:
        console:
          enabled: ${LOG_TECNICO_CONSOLE_ENABLED:true}
          pretty: ${LOG_TECNICO_CONSOLE_PRETTY:false}
        tcp:
          enabled: ${LOG_TECNICO_TCP_ENABLED:false}
      # Negócio
      srvcanal.log:
        console:
          enabled: ${LOG_SRVCANAL_CONSOLE_ENABLED:true}
        tcp:
          enabled: ${LOG_SRVCANAL_TCP_ENABLED:false}

springdoc:
  pathsToMatch: /**
  swagger-ui:
    enabled: true
    tagsSorter: alpha